# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  displayName: 'Trigger Tosca Execution'
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)\tosca_execution_client.ps1'
    arguments: '-toscaServerUrl "http://localhost:8080" -projectName "Multi-AOS" -events ''["DEX_Event"]'' -clientTimeout 3600'
    errorActionPreference: 'stop'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Tosca Results'
  inputs:
    pathToPublish: '$(Build.SourcesDirectory)\results'   # Assuming results are saved here
    artifactName: 'ToscaResults'
    publishLocation: 'Container'


